#APP
spring.application.name=dinnerSortedApp
#SERVER
server.port=8080
#CONFIG
spring.config.import=optional:file:.env[.properties]
cors.allowed.origins=http://localhost:5173,https://dinner-sorted-app.vercel.app
#OPENAI
openai.api.url=https://api.openai.com/v1
#SUPABASE
supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}