#APP
spring.application.name=dinnerSortedApp
#SERVER
server.port=8080
#CONFIG
spring.config.import=optional:file:.env[.properties]
cors.allowed.origins=http://localhost:5173,https://dinner-sorted-app.vercel.app
#OPENAI
openai.api.url=https://api.openai.com/v1
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.openai.chat.options.temperature=0.7
#SUPABASE
supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}